id: d4df4e7d-81a4-48d8-9b86-4966bb85550f
name: ProjectContext
type: c4-project
description: This is a sample project configuration for C4 model generation.
children:
- id: eeed5b4c-ac61-48b7-8e3f-015c295553dd
  type: software-system
- id: a6be7525-5305-4bfc-be9a-a8e8f562d243
  type: person
